### ISSUE TITLE
Insert "expertience report form" into "contribute form"

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/mixtures#102]
As people often try to participate sending us poor reports via the "contribute" option, I propose to modify this option as : 

```
hey wanna report your experience about this mixture ? Please fill this short anonymous form : https://framaforms.org/rapport-dexperience-pour-mixtures-1709731704

Do you have _another suggestion_ for this interaction sheet ? 
[textbox]
```

**Comment by x-yzt** [comment]
Agreed. Should we just add a link to the new form or ditch out the old contrib system (and all relevant code) entirely?

**Comment by Tridimensionnel** [comment]
Let's try to simply add a link. I made a suggestion in the first message. If people continue to wrongly use it, we'll ditch out the old system.
