### ISSUE TITLE
Add a way to use TOC on mobile devices

### ISSUE THREAD

**Issue by x-yzt** [x-yzt/mixtures#47]
Currently the TOC is only displayed on large width screens.

It would be great to think of something so it is easier to scroll through long pages on mobile devices too :)

![image](https://user-images.githubusercontent.com/62727704/211931639-1db86f47-1a39-4975-92c7-bf717c1361dd.png)

**Comment by x-yzt** [comment]
@galaad37 I can't assign you on this as you're not a project member, however I guess this would be a good first issue for you :)

**Comment by galaad37** [comment]
Would it be sufficient for mobile devices to put the TOC at the top of the page, without keeping it on the screen when the user scrolls? Or should I think about allowing to hide/show the sidebar?

**Comment by x-yzt** [comment]
I've been thinking about it a bit and I don't think one can simply put the TOC at the top of the page on mobile devices.
The point of having a TOC is to make very long content (such as https://mixtures.info/substance/mdma/) easier to navigate. A way to show/hide the sidebar regardless of the current position of the user on the page seems better to me (maybe by swiping?)
