### ISSUE TITLE
Automatically ping webarchive when a link is inserted on Mixtures

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/mixtures#75]
It would lessen the problem of dead links which will ultimately appear

**Comment by x-yzt** [comment]
Useful resources for this:

- WB endpoint to get a snapshot https://archive.org/developers/tutorial-get-snapshot-wayback.html#steps
- SPN2 docs https://docs.google.com/document/d/1Nsv52MvSjbLb2PCpHlat0gkzw0EvtSgpKHu4mk0MnrA/edit
- `fly.toml` example with Celery worker https://community.fly.io/t/preview-multi-process-apps-get-your-workers-here/2316/13
