### ISSUE TITLE
Change (simplify) the subtitle of the website

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/mixtures#76]
From "Synergies et risques liés aux interactions entre drogues"
to "Effets et risques des mélanges de drogues"
More accurate ("synergie" is a type of effect) and direct

**Comment by x-yzt** [comment]
lgtm, SEO-wise we should probably change "_Mixtures.info a pour objectif de délivrer des données vérifiables **sur les mélanges** de drogues_" to "_Mixtures.info a pour objectif de délivrer des données vérifiables **sur les interactions entre** drogues_" beneath.

EN translation has to be updated accordingly
